language: node_js
node_js:
  - "node"
  - "lts/*"
install:
  - npm install
script:
  - npm run test && npm run build
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run semantic-release"; fi
after_success:
  - codecov
